"""
src/domain/models/chat_message.py
This file defines the ChatMessageModel model used for AI interactions.
"""

from typing import Literal, TypedDict


class ChatMessageModel(TypedDict):
    """
    Represents the structure of a chat message for the OpenAI API.

    Attributes:
        role (Literal["system", "user", "assistant"]):
            Defines the role of the message sender:
            - "system": Provides system-level instructions.
            - "user": Represents input from the user.
            - "assistant": Represents responses generated by the AI.
        content (str): The actual text content of the message.
    """

    role: Literal["system", "user", "assistant"]
    content: str
